import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Header from "@/components/header";
import { DynamicBreadcrumb } from "@/components/breadcrum";
import { ScrollToTopButton } from "@/components/scroll-to-top-button";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <div className="w-full items-start">
            <SidebarTrigger className="sticky top-2 ml-2 z-50" />
            <div className="flex flex-col items-start justify-items-center min-h-[100dvh] font-[family-name:var(--font-geist-sans)] -mt-8">
              <Header />
              <div className="p-8 pt-4 sm:pt-0 pb-20 sm:p-20 w-full">
                <DynamicBreadcrumb />
                {children}
              </div>
              <ScrollToTopButton />
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
